-- Model: Make IT Model
-- Version: 6.0.0
-- Author: sonnyako <Makydon Sofiia>
-- Project: MySQL DB for Job Promoter Application "Make IT"
-- Description: Altering Project table migration

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- Altering: PROJECT

ALTER TABLE `make_it`.`PROJECT`
    CHANGE COLUMN `logo` `logo` TEXT NULL DEFAULT NULL;

ALTER TABLE `make_it`.`PROJECT`
    CHANGE COLUMN `name` `name` VARCHAR(125) NOT NULL;

ALTER TABLE `make_it`.`PROJECT`
    CHANGE COLUMN `description` `description` TEXT NOT NULL;

SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;